CREATE TABLE COFFEE(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(30),
PRICE INT,
HOWMANYLEFT INT,
PRIMARY KEY(ID)
);
CREATE TABLE USERS(
ID INT NOT NULL AUTO_INCREMENT,
NAME VARCHAR(40),
PASSWORD VARCHAR(40),
PRIMARY KEY(ID)
);
CREATE TABLE ORDERS(
ID INT NOT NULL AUTO_INCREMENT,
COFFEENAME VARCHAR(40),
USERNAME VARCHAR(40),
AMOUNT INT,
PRIMARY KEY(ID)
);